name: Package and Publish Protobuf Files

on:
  release:
    types:
      - published

jobs:
  package-protobuf:
    name: Create and Upload Protobuf ZIP to GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Install zip utility
        run: sudo apt-get install zip

      - name: Package Protobuf Files
        run: |
          zip -r protobuf-files-${{ github.event.release.tag_name }}.zip ./org/polypheny/prism

      - name: Upload ZIP to GitHub Release
        uses: actions/upload-release-asset@v2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./protobuf-files-${{ github.event.release.tag_name }}.zip
          asset_name: protobuf-files-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
