name: Run Python Generator Script

on:
  push:
    branches:
      - '**'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Documentation
        run: |
          cd doc-generator
          python generator.py "https://github.com/${{ github.repository }}" "${{ github.ref_name }}"

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit Generated Markdown Files
        run: |
          git add doc/*.md
          git commit -m "Auto-update documentation" -a || echo "No changes to commit"
          git push